batch_size: 1024
clamp: true
clamp_value: 0.1
class_embed_size: 32
dataset: ShapeNetCore
epochs: 1000
inner_dim: 256
latent_size: 128
loss_multiplier: 1
lr_latent: 0.001
lr_model: 0.0005
lr_multiplier: 0.9
lr_scheduler: true
num_layers: 8
patience: 20
pretrain_class_embed: ''
pretrain_optim_latent: ''
pretrain_optim_model: ''
pretrain_weights: ''
pretrained: false
seed: 42
sigma_regulariser: 0.01
skip_connections: true
