# Config file for benchmarking

folder_sdf: '24_07_112141' # Path containing training results i.e. model weights; stored in results/runs_sdf, example: '14_05_2023'
resolution: 128
category_ids: ['03001627'] # categories of shapes to be used in benchmark
benchmark_samples: 5 # number of shapes per category to be used for benchmark
save_output_meshes: True # If output meshes of benchmark should be saved
save_every: 1 # Indicate after how many samples the results should be saved to file

# Visible bounding box for shape completion
x_axis_ratio_bbox: 0.5 # e.g. x_axis_ratio_bbox: 0.5, visible poincloud in half the object bounding box along the x-axis
y_axis_ratio_bbox: 1
z_axis_ratio_bbox: 1

# Inference parameters for latent code optimization
epochs: 2000 # Number of epochs for latent code inference"
lr: 0.0001 # Learning rate for latent code inference
lr_scheduler: True   
lr_multiplier: 0.5 # Learning rate multiplier for the scheduler (if lr_scheduler: True)
patience: 100 # Patience for latent code inference (if lr_scheduler: True)
sigma_regulariser: 0.01 # Regulariser for the loss function
clamp: True # Clip the network prediction
clamp_value: 0.1 # Clipping value